# name: Build & Deploy (Production)

# on:
#   push:
#     branches:
#      - master
#     paths:
#      - 'packages/server/**'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.v

#       - name: Deploy
#         run: echo "Deployed"